// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NupArCXN1Cq1YqniZgJ5bWTHTVQZ3uY',
    appId: '1:957789091071:web:63792c4ff9429ac82bc8ca',
    messagingSenderId: '957789091071',
    projectId: 'm3-myfirstflutterproject2022',
    authDomain: 'm3-myfirstflutterproject2022.firebaseapp.com',
    storageBucket: 'm3-myfirstflutterproject2022.appspot.com',
    measurementId: 'G-80K2KQNMDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3TovKUfrKwMAmIIaEnFEbOAAjdSijj0',
    appId: '1:957789091071:android:96f3740c5f87d8652bc8ca',
    messagingSenderId: '957789091071',
    projectId: 'm3-myfirstflutterproject2022',
    storageBucket: 'm3-myfirstflutterproject2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfmCHlvQEDn14hZJoNX7WzHjHzDjQY-50',
    appId: '1:957789091071:ios:d75b41ff58cf9a7f2bc8ca',
    messagingSenderId: '957789091071',
    projectId: 'm3-myfirstflutterproject2022',
    storageBucket: 'm3-myfirstflutterproject2022.appspot.com',
    iosClientId: '957789091071-konf1duvf41om4kalourg630qmsslpg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfmCHlvQEDn14hZJoNX7WzHjHzDjQY-50',
    appId: '1:957789091071:ios:d75b41ff58cf9a7f2bc8ca',
    messagingSenderId: '957789091071',
    projectId: 'm3-myfirstflutterproject2022',
    storageBucket: 'm3-myfirstflutterproject2022.appspot.com',
    iosClientId: '957789091071-konf1duvf41om4kalourg630qmsslpg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
